name: autocrop-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.6,<3.9
  - opencv 
  - regex 
  - psutil
  - pip:
    - https://github.com/SGenheden/auto-crop/archive/0.0.3.tar.gz
